apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zetta1demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        namespace: zetta1demo
  template:
    metadata:
      name: '{{cluster}}-zetta1demo'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/g0t3t/zettademo1.git'
        targetRevision: HEAD
        path: k8s 
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - PruneLast=true