name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., "v1.0", "test")'
        required: true
        default: 'test'
  push:
    branches: [ "main" ]

env:
  REGISTRY: zettademo1acr.azurecr.io
  APP_NAME: zetta1demo
  K8S_MANIFEST: k8s/manifest.yaml

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.event.inputs.image_tag || 'test' }}
          ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Kubernetes manifest
      run: |
        TAG=${{ github.event.inputs.image_tag || 'test' }}
        sed -i "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.APP_NAME }}:$TAG|g" ${{ env.K8S_MANIFEST }}
        
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ${{ env.K8S_MANIFEST }}
        git commit -m "CI: Update image to $TAG"
        git push